version: 2

references:

  ruby_image: &ruby_image
    circleci/ruby:2.3.3

  mysql_container_config: &mysql_container_config
    docker:
      - image: *ruby_image
        environment:
          DB_HOST=127.0.0.1
      - image: circleci/mysql:5.6.39
        environment:
          MYSQL_DATABASE=immortal_db

  sqlite_container_config: &sqlite_container_config
    docker:
      - image: *ruby_image

  install_bundler: &install_bundler
    run:
      name: Install Bundler
      command: |
        gem install bundler
        gem cleanup bundler

  install_gems: &install_gems
    run:
      name: Install Gems
      command: bundle install

  appraisal_install: &appraisal_install
    run:
      name: Appraisal Install
      command: bundle exec appraisal install

  appraisal_rspec: &appraisal_rspec
    run:
      name: Appraisal RSpec
      command: bundle exec appraisal rspec

jobs:
  test_on_mysql:
    <<: *mysql_container_config
    environment:
      - CONFIG_MYSQL=true
      - DB_PORT=3306
    steps:
      - checkout
      - *install_bundler
      - *install_gems
      - *appraisal_install
      - *appraisal_rspec
  test_on_sqlite:
    <<: *sqlite_container_config
    steps:
      - checkout
      - *install_bundler
      - *install_gems
      - *appraisal_install
      - *appraisal_rspec

workflows:
  version: 2
  commit:
    jobs:
      - test_on_mysql
      - test_on_sqlite
